name: api-iot
channels:
  - conda-forge
  - defaults
dependencies:
  - flask=2.0.3
  - numpy=1.21.6
  - pika=1.2.0
  - pip=21.2.4
  - pyserial=3.5
  - python=3.8.12
  - rabbitmq-server=3.10.5
  - streamlit=1.10.0